Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2018-05, with the labels that each got.

#74 Partial support for authenticated peers
  src/yggdrasil/admin.go
  src/yggdrasil/config/config.go
  src/yggdrasil/core.go
  src/yggdrasil/debug.go
  src/yggdrasil/peer.go
  src/yggdrasil/tcp.go
  src/yggdrasil/udp.go
  yggdrasil.go
Labels: needs testing

#76 Use HJSON for config instead of JSON
  src/yggdrasil/config/config.go
  yggdrasil.go
Labels: enhancement

#86 Show IPv6 address and subnet on startup
  src/yggdrasil/admin.go
  src/yggdrasil/core.go
  yggdrasil.go
  yggdrasilctl.go
Labels: enhancement

#87 Update configuration names and update multicast behaviour
  contrib/deb/generate.sh
  misc/sim/treesim.go
  src/yggdrasil/admin.go
  src/yggdrasil/config/config.go
  src/yggdrasil/core.go
  src/yggdrasil/debug.go
  src/yggdrasil/multicast.go
  src/yggdrasil/peer.go
  src/yggdrasil/tcp.go
  src/yggdrasil/udp.go
  yggdrasil.go
  yggdrasilctl.go
Labels: enhancement

#89 Fix debian normalisation in postinst
  contrib/deb/generate.sh
Labels: bug

#90 Add getMulticastInterfaces and getSelf to yggdrasilctl
  src/yggdrasil/admin.go
  yggdrasilctl.go
Labels: enhancement

#93 Fix MulticastInterfaces and accidental truncation of addresses on macOS/BSD
  src/yggdrasil/multicast.go
  src/yggdrasil/tun_bsd.go
  src/yggdrasil/tun_darwin.go
  yggdrasil.go
Labels: bug

#97 Set allowed encryption keys after start
  yggdrasil.go
Labels: bug
