Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2018-06, with the labels that each got.

#98 Admin "dot" style changes
  src/yggdrasil/admin.go
Labels: philosophical, unfinished

#102 Fix IfName 'none'
  src/yggdrasil/tun.go
Labels: bug

#117 closed channel send bugfix
  src/yggdrasil/peer.go
Labels: bug

#115 v0.2 changes
  README.md
  VERSION
  build
  misc/sim/treesim.go
  src/yggdrasil/address.go
  src/yggdrasil/admin.go
  src/yggdrasil/config/config.go
  src/yggdrasil/core.go
  src/yggdrasil/crypto.go
  src/yggdrasil/debug.go
  src/yggdrasil/dht.go
  src/yggdrasil/icmpv6.go
  src/yggdrasil/multicast.go
  src/yggdrasil/peer.go
  src/yggdrasil/release.go
  src/yggdrasil/router.go
  src/yggdrasil/search.go
  src/yggdrasil/session.go
  src/yggdrasil/signature.go
  src/yggdrasil/switch.go
  src/yggdrasil/tcp.go
  src/yggdrasil/tun.go
  src/yggdrasil/tun_bsd.go
  src/yggdrasil/tun_darwin.go
  src/yggdrasil/tun_freebsd.go
  src/yggdrasil/tun_linux.go
  src/yggdrasil/tun_netbsd.go
  src/yggdrasil/tun_openbsd.go
  src/yggdrasil/tun_other.go
  src/yggdrasil/tun_windows.go
  src/yggdrasil/udp.go
  src/yggdrasil/util.go
  src/yggdrasil/version.go
  src/yggdrasil/wire.go
Labels: BREAKING (!)

#121 Fix launchd script path and amend debian control file
  contrib/deb/generate.sh
  contrib/macos/yggdrasil.plist
Labels: enhancement

#122 Address prefix change
  src/yggdrasil/address.go
  src/yggdrasil/admin.go
  src/yggdrasil/core.go
  src/yggdrasil/icmpv6.go
  src/yggdrasil/tun_darwin.go
Labels: BREAKING (!)

#123 Fix debian control file
  contrib/deb/generate.sh
Labels: bug

#129 Convert config from UTF-16 if a BOM is found
  yggdrasil.go
Labels: enhancement, windows

#130 Version 0.2.1
  .circleci/config.yml
  README.md
  contrib/deb/generate.sh
  contrib/macos/yggdrasil.plist
  src/yggdrasil/address.go
  src/yggdrasil/admin.go
  src/yggdrasil/core.go
  src/yggdrasil/debug.go
  src/yggdrasil/dht.go
  src/yggdrasil/icmpv6.go
  src/yggdrasil/session.go
  src/yggdrasil/switch.go
  src/yggdrasil/tcp.go
  src/yggdrasil/tun_darwin.go
  yggdrasil.go
Labels: BREAKING

#135 Fix typo for big-endian BOM
  yggdrasil.go
Labels: bug

#143 Change box_pub_key to key in admin API
  src/yggdrasil/admin.go
Labels: enhancement
