Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2018-12, with the labels that each got.

#217 Add -json flag for -genconf and -normaliseconf
  yggdrasil.go
Labels: enhancement

#223 Try to SO_REUSEPORT on multicast socket
  src/yggdrasil/multicast.go
  src/yggdrasil/multicast_other.go
  src/yggdrasil/multicast_unix.go
  src/yggdrasil/multicast_windows.go
Labels: enhancement, needs testing

#219 Tag releases in master using CI
  .circleci/config.yml
  contrib/.DS_Store
  contrib/semver/version.sh
Labels: enhancement

#226 Imprint version number onto builds
  CHANGELOG.md
  VERSION
  build
  contrib/semver/name.sh
  contrib/semver/version.sh
  src/yggdrasil/admin.go
  src/yggdrasil/core.go
  yggdrasil.go
  yggdrasilctl.go
Labels: enhancement

#227 convert to go module
  .circleci/config.yml
  CHANGELOG.md
  README.md
  build
  cmd/yggdrasil/main.go
  cmd/yggdrasilctl/main.go
  contrib/.DS_Store
  contrib/config/yggdrasilconf.go
  contrib/deb/generate.sh
  contrib/semver/name.sh
  contrib/semver/version.sh
  go.mod
  go.sum
  misc/genkeys.go
  misc/sim/run-sim
  misc/sim/treesim.go
  src/config/config.go
  src/config/i2p.go
  src/config/tor.go
  src/defaults/defaults.go
  src/defaults/defaults_darwin.go
  src/defaults/defaults_freebsd.go
  src/defaults/defaults_linux.go
  src/defaults/defaults_netbsd.go
  src/defaults/defaults_openbsd.go
  src/defaults/defaults_other.go
  src/defaults/defaults_windows.go
  src/yggdrasil/admin.go
  src/yggdrasil/core.go
  src/yggdrasil/debug.go
  src/yggdrasil/switch.go
  src/yggdrasil/tun.go
Labels: needs testing

#229 Fix circleci/semver bugs
  .circleci/config.yml
  contrib/semver/version.sh
Labels: bug

#234 Allow disabling admin socket
  CHANGELOG.md
  src/config/config.go
  src/yggdrasil/admin.go
Labels: enhancement

#236 Add starting point for an RPM spec file
  CHANGELOG.md
  contrib/rpm/yggdrasil.spec
Labels: linux

#238 Use AF_UNIX socket by default for admin API
  CHANGELOG.md
  cmd/yggdrasilctl/main.go
  src/defaults/defaults.go
  src/defaults/defaults_darwin.go
  src/defaults/defaults_freebsd.go
  src/defaults/defaults_linux.go
  src/defaults/defaults_netbsd.go
  src/defaults/defaults_openbsd.go
  src/defaults/defaults_other.go
  src/defaults/defaults_windows.go
  src/yggdrasil/admin.go
Labels: enhancement, freebsd, linux, macos, netbsd, openbsd

#231 Version 0.3
  .circleci/config.yml
  CHANGELOG.md
  Dockerfile
  LICENSE
  README.md
  VERSION
  build
  cmd/yggdrasil/main.go
  cmd/yggdrasilctl/main.go
  contrib/config/yggdrasilconf.go
  contrib/deb/generate.sh
  contrib/docker/Dockerfile
  contrib/docker/entrypoint.sh
  contrib/macos/create-pkg.sh
  contrib/rpm/yggdrasil.spec
  contrib/semver/name.sh
  contrib/semver/version.sh
  doc/README.md
  doc/Whitepaper.md
  go.mod
  go.sum
  misc/genkeys.go
  misc/sim/run-sim
  misc/sim/treesim.go
  src/config/config.go
  src/config/i2p.go
  src/config/tor.go
  src/defaults/defaults.go
  src/defaults/defaults_darwin.go
  src/defaults/defaults_freebsd.go
  src/defaults/defaults_linux.go
  src/defaults/defaults_netbsd.go
  src/defaults/defaults_openbsd.go
  src/defaults/defaults_other.go
  src/defaults/defaults_windows.go
  src/yggdrasil/admin.go
  src/yggdrasil/ckr.go
  src/yggdrasil/core.go
  src/yggdrasil/debug.go
  src/yggdrasil/dht.go
  src/yggdrasil/icmpv6.go
  src/yggdrasil/multicast.go
  src/yggdrasil/multicast_other.go
  src/yggdrasil/multicast_unix.go
  src/yggdrasil/multicast_windows.go
  src/yggdrasil/peer.go
  src/yggdrasil/router.go
  src/yggdrasil/search.go
  src/yggdrasil/session.go
  src/yggdrasil/signature.go
  src/yggdrasil/switch.go
  src/yggdrasil/tcp.go
  src/yggdrasil/tun.go
Labels: release

#245 Update debian package behavior
  contrib/deb/generate.sh
Labels: linux

#253 Fix bug in yggdrasilctl where -endpoint gets ignored
  cmd/yggdrasilctl/main.go
Labels: bug

#254 Fix panic if Peers or InterfacePeers is commented out
  cmd/yggdrasil/main.go
Labels: bug

#246 NodeInfo support
  src/config/config.go
  src/yggdrasil/admin.go
  src/yggdrasil/core.go
  src/yggdrasil/nodeinfo.go
  src/yggdrasil/peer.go
  src/yggdrasil/router.go
  src/yggdrasil/wire.go
Labels: enhancement

#258 Make yggdrasilctl less crashy
  cmd/yggdrasilctl/main.go
Labels: bug

#289 Don't process ICMPv6 messages when in TUN mode
  src/yggdrasil/icmpv6.go
  src/yggdrasil/tun.go
Labels: bug

#291 Version 0.3.2
  .circleci/config.yml
  CHANGELOG.md
  clean
  cmd/yggdrasil/main.go
  contrib/deb/generate.sh
  contrib/semver/version.sh
  doc/Whitepaper.md
  src/config/config.go
  src/yggdrasil/core.go
  src/yggdrasil/dht.go
  src/yggdrasil/icmpv6.go
  src/yggdrasil/nodeinfo.go
  src/yggdrasil/router.go
  src/yggdrasil/tun.go
  src/yggdrasil/wire.go
Labels: release

#299 getNodeInfo: Show own info if box_pub_key/coords not specified
  src/yggdrasil/admin.go
Labels: enhancement
