Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2019-11, with the labels that each got.

#604 Add -address and -subnet command line options to cmd/yggdrasil
  cmd/yggdrasil/main.go
Labels: enhancement, feature request

#606 fix deadlock when AddPeer fails
  src/yggdrasil/api.go
Labels: bug

#597 FIX: Systemd: typo in directive
  contrib/systemd/yggdrasil.service
Labels: bug, linux

#605 Src version: return unknown not yggdrasilctl
  src/version/version.go
Labels: bug

#608 Improve MTU handling
  src/tuntap/tun.go
  src/tuntap/tun_bsd.go
  src/tuntap/tun_darwin.go
  src/tuntap/tun_linux.go
  src/tuntap/tun_other.go
  src/tuntap/tun_windows.go
Labels: bug

#609 Move genkeys into cmd/
  build
  cmd/genkeys/main.go
Labels: enhancement

#612 Fix couple of issues with MTU bounds
  src/tuntap/tun.go
  src/tuntap/tun_linux.go
Labels: bug

#613 Add API functions for manipulating maximum session MTU
  CHANGELOG.md
  src/tuntap/tun.go
  src/yggdrasil/api.go
  src/yggdrasil/session.go
Labels: bug, merge when ready

#610 Version 0.3.12
  CHANGELOG.md
  build
  cmd/genkeys/main.go
  cmd/yggdrasil/main.go
  contrib/systemd/yggdrasil.service
  src/multicast/multicast.go
  src/tuntap/tun.go
  src/tuntap/tun_bsd.go
  src/tuntap/tun_darwin.go
  src/tuntap/tun_linux.go
  src/tuntap/tun_other.go
  src/tuntap/tun_windows.go
  src/version/version.go
  src/yggdrasil/api.go
  src/yggdrasil/search.go
  src/yggdrasil/session.go
  src/yggdrasil/tcp.go
  src/yggdrasil/tcp_darwin.go
  src/yggdrasil/tcp_linux.go
  src/yggdrasil/tcp_other.go
Labels: release

#620 Update yggdrasil.service
  contrib/systemd/yggdrasil.service
Labels: bug, linux

#619 Bugfix
  src/yggdrasil/link.go
  src/yggdrasil/switch.go
Labels: bug, needs testing

#621 Appveyor MSI builds for Windows
  appveyor.yml
  contrib/msi/build-msi.sh
Labels: windows

#622 More MSI updates
  contrib/msi/build-msi.sh
Labels: windows

#618 Replace Water library with Wireguard's tun package (inc. Wintun support on Windows)
  .circleci/config.yml
  appveyor.yml
  contrib/msi/build-msi.sh
  go.mod
  go.sum
  src/config/config.go
  src/defaults/defaults.go
  src/defaults/defaults_darwin.go
  src/defaults/defaults_freebsd.go
  src/defaults/defaults_linux.go
  src/defaults/defaults_netbsd.go
  src/defaults/defaults_openbsd.go
  src/defaults/defaults_other.go
  src/defaults/defaults_windows.go
  src/tuntap/admin.go
  src/tuntap/icmpv6.go
  src/tuntap/iface.go
  src/tuntap/tun.go
  src/tuntap/tun_bsd.go
  src/tuntap/tun_darwin.go
  src/tuntap/tun_linux.go
  src/tuntap/tun_other.go
  src/tuntap/tun_windows.go
Labels: enhancement, merge when ready, needs testing, windows

#625 Fix typos
  CHANGELOG.md
  cmd/genkeys/main.go
  doc/Whitepaper.md
  misc/sim/treesim-forward.py
  misc/sim/treesim.go
  src/address/address.go
  src/config/config.go
  src/crypto/crypto.go
  src/tuntap/conn.go
  src/yggdrasil/conn.go
  src/yggdrasil/core_test.go
  src/yggdrasil/dht.go
  src/yggdrasil/dialer.go
  src/yggdrasil/link.go
  src/yggdrasil/peer.go
  src/yggdrasil/search.go
  src/yggdrasil/session.go
  src/yggdrasil/switch.go
  src/yggdrasil/version.go
Labels: enhancement
