Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2019-08, with the labels that each got.

#477 Update CHANGELOG.md
  CHANGELOG.md
Labels: to do

#485 Bugfix
  src/.DS_Store
  src/yggdrasil/router.go
Labels: bug

#491 Fix the old flowkey stuff so congestion control actually works...
  src/tuntap/conn.go
  src/util/util.go
  src/yggdrasil/conn.go
  src/yggdrasil/router.go
  src/yggdrasil/session.go
Labels: bug

#492 Transform Listen statement to new format if needed
  cmd/yggdrasil/main.go
Labels: bug

#498 Search fixes
  src/yggdrasil/conn.go
  src/yggdrasil/search.go
Labels: bug

#499 Prevent session leaks or blocking if the listener is busy
  go.sum
  src/yggdrasil/session.go
Labels: bug

#502 Try to fix leaks in #501
  src/yggdrasil/link.go
Labels: bug

#504 Use new netlink library (fixes #493)
  go.mod
  go.sum
  src/tuntap/tun_linux.go
Labels: to do

#506 Switch priority change
  go.sum
  src/yggdrasil/switch.go
Labels: bug, needs testing

#505 Version 0.3.7
  CHANGELOG.md
  README.md
  build
  cmd/yggdrasil/main.go
  cmd/yggdrasilctl/main.go
  go.mod
  go.sum
  src/admin/admin.go
  src/tuntap/conn.go
  src/tuntap/iface.go
  src/tuntap/tun_linux.go
  src/util/util.go
  src/util/workerpool.go
  src/version/version.go
  src/yggdrasil/api.go
  src/yggdrasil/conn.go
  src/yggdrasil/core.go
  src/yggdrasil/dialer.go
  src/yggdrasil/link.go
  src/yggdrasil/nodeinfo.go
  src/yggdrasil/router.go
  src/yggdrasil/search.go
  src/yggdrasil/session.go
  src/yggdrasil/stream.go
  src/yggdrasil/switch.go
  src/yggdrasil/wire.go
Labels: release

#512 Cryptokey routing changes
  cmd/yggdrasil/main.go
  src/config/config.go
  src/tuntap/admin.go
  src/tuntap/ckr.go
  src/tuntap/conn.go
  src/tuntap/iface.go
Labels: enhancement

#516 Version 0.3.8
  CHANGELOG.md
  cmd/yggdrasil/main.go
  go.mod
  go.sum
  src/config/config.go
  src/tuntap/admin.go
  src/tuntap/ckr.go
  src/tuntap/conn.go
  src/tuntap/iface.go
  src/yggdrasil/conn.go
  src/yggdrasil/debug.go
  src/yggdrasil/dialer.go
  src/yggdrasil/link.go
  src/yggdrasil/peer.go
  src/yggdrasil/router.go
  src/yggdrasil/session.go
  src/yggdrasil/stream.go
  src/yggdrasil/switch.go
Labels: release

#520 fix memory leak in session nonce map
  src/yggdrasil/session.go
Labels: bug

#519 Actors
  cmd/yggdrasil/main.go
  go.mod
  go.sum
  src/multicast/multicast.go
  src/tuntap/ckr.go
  src/tuntap/conn.go
  src/tuntap/iface.go
  src/tuntap/tun.go
  src/yggdrasil/api.go
  src/yggdrasil/conn.go
  src/yggdrasil/core.go
  src/yggdrasil/debug.go
  src/yggdrasil/dht.go
  src/yggdrasil/dialer.go
  src/yggdrasil/link.go
  src/yggdrasil/listener.go
  src/yggdrasil/nodeinfo.go
  src/yggdrasil/peer.go
  src/yggdrasil/router.go
  src/yggdrasil/search.go
  src/yggdrasil/session.go
  src/yggdrasil/switch.go
  src/yggdrasil/tcp.go
Labels: needs testing, philosophical, unfinished
