Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2019-07, with the labels that each got.

#447 Another Conn bugfix
  src/yggdrasil/conn.go
Labels: bug

#453 Bug fixes
  cmd/yggdrasil/main.go
  src/multicast/multicast.go
  src/tuntap/iface.go
  src/tuntap/tun.go
  src/yggdrasil/core.go
Labels: bug

#455 Fix TAP mode
  src/tuntap/ckr.go
  src/tuntap/icmpv6.go
  src/tuntap/iface.go
  src/tuntap/tun.go
  src/tuntap/tun_windows.go
Labels: bug

#395 Handle admin socket error cases better
  src/admin/admin.go
Labels: enhancement

#460 Fix #413
  src/crypto/crypto.go
  src/yggdrasil/core.go
Labels: bug, merge when ready

#433 Try to build the new RPM using CircleCI
  .circleci/config.yml
Labels: linux, merge when ready

#461 Try to fix TUN/TAP conn reader leakage
  src/tuntap/conn.go
Labels: bug

#462 fix possible unsafe memory use in Conn.Read
  src/yggdrasil/conn.go
Labels: bug

#466 Fix a couple of Windows bugs
  .circleci/config.yml
  go.mod
  go.sum
  src/tuntap/tun_windows.go
Labels: bug, windows

#470 Redirect Conn session closure errors to debug channel
  src/tuntap/conn.go
Labels: enhancement, merge when ready

#469 Don't send IP back twice with getPeers
  src/admin/admin.go
Labels: bug, merge when ready

#467 Send PPROF output text to stderr
  src/yggdrasil/debug.go
Labels: bug, merge when ready

#473 Possible fix for macos self-traffic
  .circleci/config.yml
  src/tuntap/tun_darwin.go
  src/yggdrasil/search.go
Labels: bug, needs testing

#474 Various API changes and simplifications to fix mobile builds
  build
  src/admin/admin.go
  src/config/config.go
  src/dummy/dummy.go
  src/mobile/awdl.go
  src/mobile/mobile.go
  src/mobile/mobile_android.go
  src/mobile/mobile_ios.go
  src/multicast/multicast.go
  src/tuntap/ckr.go
  src/tuntap/conn.go
  src/tuntap/tun.go
  src/tuntap/tun_dummy.go
  src/yggdrasil/api.go
  src/yggdrasil/conn.go
  src/yggdrasil/core.go
  src/yggdrasil/nodeinfo.go
  src/yggdrasil/router.go
  src/yggdrasil/wire.go
Labels: android, ios

#476 Update build script
  build
Labels: enhancement
