Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2019-06, with the labels that each got.

#429 fix issue with sessions dying and never being fixed
  src/yggdrasil/conn.go
Labels: bug

#431 Add multicast interfaces to platform-specific defaults
  src/config/config.go
  src/defaults/defaults.go
  src/defaults/defaults_darwin.go
  src/defaults/defaults_freebsd.go
  src/defaults/defaults_linux.go
  src/defaults/defaults_netbsd.go
  src/defaults/defaults_openbsd.go
  src/defaults/defaults_other.go
  src/defaults/defaults_windows.go
Labels: enhancement, merge when ready

#432 Implement session gatekeeper functions
  cmd/yggdrasil/main.go
  src/yggdrasil/api.go
  src/yggdrasil/session.go
Labels: enhancement, merge when ready

#440 Add support for logging to file or syslog instead of stdout
  cmd/yggdrasil/main.go
  src/yggdrasil/api.go
Labels: enhancement

#438 Try and solidify multicast interface behavior
  src/multicast/admin.go
  src/multicast/multicast.go
  src/multicast/multicast_darwin.go
Labels: enhancement

#444 Dial fixes
  src/yggdrasil/conn.go
  src/yggdrasil/dialer.go
  src/yggdrasil/router.go
  src/yggdrasil/session.go
Labels: bug

#445 more bugfixes
  src/yggdrasil/conn.go
  src/yggdrasil/session.go
Labels: bug

#446 Bugfixes
  src/tuntap/iface.go
  src/yggdrasil/api.go
  src/yggdrasil/conn.go
Labels: bug
