Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2019-02, with the labels that each got.

#322 Idle link logic changes
  src/util/util.go
  src/yggdrasil/debug.go
  src/yggdrasil/link.go
  src/yggdrasil/peer.go
  src/yggdrasil/router.go
  src/yggdrasil/switch.go
Labels: needs testing

#331 Don't build 32-bit builds for macOS
  .circleci/config.yml
Labels: macos

#330 Remove yggdrasil-resume.service
  contrib/deb/generate.sh
  contrib/systemd/yggdrasil-resume.service
  contrib/systemd/yggdrasil.service
Labels: linux

#334 Bugfix
  misc/run-twolink-test
  src/yggdrasil/link.go
  src/yggdrasil/switch.go
Labels: bug
