Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2019-09, with the labels that each got.

#527 Bugfix
  src/yggdrasil/search.go
Labels: bug

#534 Fix race between router and dial code
  src/yggdrasil/conn.go
Labels: bug

#542 Switch
  src/yggdrasil/switch.go
Labels: bug

#548 Bugfixes
  cmd/yggdrasil/main.go
  src/multicast/multicast.go
  src/multicast/multicast_darwin.go
  src/yggdrasil/conn.go
  src/yggdrasil/core.go
  src/yggdrasil/link.go
  src/yggdrasil/session.go
  src/yggdrasil/tcp.go
Labels: bug

#551 Gradually increase multicast interval from startup
  src/multicast/multicast.go
Labels: enhancement

#554 Switch
  src/yggdrasil/switch.go
Labels: bug

#528 Documentation updates
  src/address/address.go
  src/config/config.go
  src/crypto/crypto.go
  src/util/bytes_mobile.go
  src/util/bytes_other.go
  src/util/cancellation.go
  src/util/util.go
  src/yggdrasil/api.go
  src/yggdrasil/conn.go
  src/yggdrasil/doc.go
Labels: help wanted, to do, unfinished

#560 Packet length checks and logging
  src/tuntap/iface.go
  src/util/cancellation.go
Labels: bug

#559 Changelog for v0.3.9
  CHANGELOG.md
Labels: merge when ready
