Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2019-10, with the labels that each got.

#566 CKR deadlock fix
  src/tuntap/conn.go
  src/yggdrasil/conn.go
Labels: bug

#569 Enable bbr for tcp sockets on linux
  go.mod
  go.sum
  src/yggdrasil/tcp_linux.go
  src/yggdrasil/tcp_other.go
Labels: philosophical

#570 fix nil pointer dereference in yggdrasil.Conn.search
  src/yggdrasil/conn.go
Labels: bug

#571 Version 0.3.10
  CHANGELOG.md
  contrib/systemd/yggdrasil.service
  go.mod
  go.sum
  src/tuntap/conn.go
  src/yggdrasil/conn.go
  src/yggdrasil/core_test.go
  src/yggdrasil/tcp_linux.go
  src/yggdrasil/tcp_other.go
Labels: release

#574 Search bugfix
  src/yggdrasil/search.go
Labels: bug

#580 fix incorrectly held mutex in ckr getPublicKeyForAddress
  src/tuntap/ckr.go
Labels: bug

#584 systemd: Allow ExecStartPre failures
  contrib/systemd/yggdrasil.service
Labels: bug

#586 Enable Linux armel builds in CircleCI
  .circleci/config.yml
Labels: feature request

#588 Initial connection upgrade/TLS steganography
  src/yggdrasil/api.go
  src/yggdrasil/link.go
  src/yggdrasil/tcp.go
  src/yggdrasil/tls.go
Labels: merge when ready, transports

#590 No longer use atomic for isOpen in multicast
  src/multicast/multicast.go
Labels: bug

#583 Define module.Module interface
  cmd/yggdrasil/main.go
  src/admin/admin.go
  src/module/module.go
  src/tuntap/tun.go
Labels: enhancement, merge when ready

#591 Changelog for v0.3.11
  CHANGELOG.md
Labels: merge when ready

#587 Version 0.3.11
  .circleci/config.yml
  CHANGELOG.md
  README.md
  cmd/yggdrasil/main.go
  contrib/systemd/yggdrasil.service
  go.mod
  go.sum
  src/address/address.go
  src/admin/admin.go
  src/module/module.go
  src/multicast/multicast.go
  src/tuntap/ckr.go
  src/tuntap/conn.go
  src/tuntap/iface.go
  src/tuntap/tun.go
  src/yggdrasil/api.go
  src/yggdrasil/conn.go
  src/yggdrasil/dialer.go
  src/yggdrasil/link.go
  src/yggdrasil/listener.go
  src/yggdrasil/search.go
  src/yggdrasil/tcp.go
  src/yggdrasil/tls.go
Labels: release

#594 fix a crash when shutting down if no multicast interfaces are configured
  src/multicast/multicast.go
Labels: bug

#595 Fix data race
  src/yggdrasil/search.go
Labels: bug
