Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2019-12, with the labels that each got.

#628 Fix return value in Multicast.Stop()
  src/multicast/multicast.go
Labels: bug

#629 Use loglevel instead comma-separated list of logging
  cmd/yggdrasil/main.go
Labels: enhancement

#634 MSI bugfixes
  contrib/msi/build-msi.sh
Labels: windows
