Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2019-03, with the labels that each got.

#350 Wake AWDL for multicast peering on macOS
  .circleci/config.yml
  src/yggdrasil/multicast.go
  src/yggdrasil/multicast_darwin.go
  src/yggdrasil/multicast_other.go
  src/yggdrasil/multicast_unix.go
  src/yggdrasil/multicast_windows.go
Labels: enhancement, macos

#356 Try to clean up UNIX admin socket
  src/yggdrasil/admin.go
Labels: enhancement

#358 Add a timeout on the UNIX admin socket check
  src/yggdrasil/admin.go
Labels: enhancement

#359 Fix macOS package
  .circleci/config.yml
Labels: bug

#364 Fix getTunTap
  src/yggdrasil/admin.go
Labels: bug

#365 Add getTunnelRouting and setTunnelRouting
  src/yggdrasil/admin.go
Labels: enhancement

#369 Fix getRoutes
  cmd/yggdrasilctl/main.go
Labels: bug

#360 Support for multiple listeners
  CHANGELOG.md
  cmd/yggdrasil/main.go
  src/config/config.go
  src/config/i2p.go
  src/config/tor.go
  src/util/util.go
  src/yggdrasil/admin.go
  src/yggdrasil/awdl.go
  src/yggdrasil/core.go
  src/yggdrasil/debug.go
  src/yggdrasil/link.go
  src/yggdrasil/multicast.go
  src/yggdrasil/peer.go
  src/yggdrasil/router.go
  src/yggdrasil/tcp.go
  src/yggdrasil/tcp_darwin.go
  src/yggdrasil/tcp_other.go
Labels: enhancement, needs testing, transports

#371 Fix bugs from multilink branch (#360)
  src/yggdrasil/multicast.go
  src/yggdrasil/tcp.go
Labels: bug

#373 Add AppArmor profile
  contrib/apparmor/usr.bin.yggdrasil
Labels: linux

#377 AWDL fixes for macOS
  src/yggdrasil/multicast.go
  src/yggdrasil/multicast_darwin.go
  src/yggdrasil/multicast_other.go
  src/yggdrasil/multicast_unix.go
  src/yggdrasil/multicast_windows.go
Labels: bug, macos

#378 Add LinkLocalTCPPort option
  CHANGELOG.md
  src/config/config.go
  src/yggdrasil/multicast.go
Labels: enhancement

#374 Version 0.3.4
  .circleci/config.yml
  CHANGELOG.md
  cmd/yggdrasil/main.go
  cmd/yggdrasilctl/main.go
  contrib/apparmor/usr.bin.yggdrasil
  contrib/busybox-init/S42yggdrasil
  contrib/macos/yggdrasil.plist
  contrib/openrc/yggdrasil
  misc/sim/treesim.go
  src/config/config.go
  src/config/i2p.go
  src/config/tor.go
  src/util/util.go
  src/yggdrasil/admin.go
  src/yggdrasil/awdl.go
  src/yggdrasil/core.go
  src/yggdrasil/debug.go
  src/yggdrasil/link.go
  src/yggdrasil/multicast.go
  src/yggdrasil/multicast_darwin.go
  src/yggdrasil/multicast_other.go
  src/yggdrasil/multicast_unix.go
  src/yggdrasil/multicast_windows.go
  src/yggdrasil/peer.go
  src/yggdrasil/router.go
  src/yggdrasil/session.go
  src/yggdrasil/switch.go
  src/yggdrasil/tcp.go
  src/yggdrasil/tcp_darwin.go
  src/yggdrasil/tcp_other.go
Labels: release

#379 Fix AllowedEncryptionPublicKeys
  src/config/config.go
  src/yggdrasil/link.go
  src/yggdrasil/tcp.go
Labels: bug

#380 Re-order config, update default Listen
  cmd/yggdrasil/main.go
  src/config/config.go
  src/yggdrasil/mobile.go
Labels: enhancement

#383 Handle cases where link-local addresses may disappear or change
  CHANGELOG.md
  src/yggdrasil/multicast.go
Labels: bug
