Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2020-05, with the labels that each got.

#686 maybe fix multicast deadlock on darwin
  src/multicast/multicast_darwin.go
Labels: bug

#687 Fix hjson dependency?
  go.mod
  go.sum
Labels: windows

#685 Public key pinning support
  src/yggdrasil/link.go
  src/yggdrasil/tcp.go
Labels: enhancement, needs testing

#696 Bugfix
  src/yggdrasil/conn.go
Labels: bug

#692 Misc updates for the future branch
  src/yggdrasil/dht.go
  src/yggdrasil/link.go
  src/yggdrasil/peer.go
  src/yggdrasil/switch.go
Labels: needs testing, unfinished

#693 Update queue behavior
  src/yggdrasil/api.go
  src/yggdrasil/core.go
  src/yggdrasil/link.go
  src/yggdrasil/packetqueue.go
  src/yggdrasil/peer.go
  src/yggdrasil/router.go
  src/yggdrasil/simlink.go
  src/yggdrasil/stream.go
  src/yggdrasil/switch.go
  src/yggdrasil/tcp.go
  src/yggdrasil/tcp_linux.go
  src/yggdrasil/tls.go
Labels: needs testing, unfinished

#700 Multicast
  src/multicast/multicast.go
  src/multicast/multicast_darwin.go
Labels: bug, needs testing

#705 Ygg-over-ygg bugfix
  src/yggdrasil/tcp.go
Labels: bug, needs testing

#706 More buffer fine-tuning
  src/yggdrasil/link.go
  src/yggdrasil/peer.go
  src/yggdrasil/router.go
Labels: needs testing

#704 Faster queue logic
  src/yggdrasil/packetqueue.go
Labels: needs testing

#702 Precompute more for the switch lookup table
  src/yggdrasil/switch.go
Labels: needs testing
