Repository yggdrasil-network/yggdrasil-go, pull requests merged in 2020-01, with the labels that each got.

#644 docker: build and copy genkeys
  contrib/docker/Dockerfile
Labels: docker

#645 Actorise NodeInfo
  src/yggdrasil/api.go
  src/yggdrasil/nodeinfo.go
  src/yggdrasil/router.go
Labels: bug

#636 util: fix possible OOB in IPv4 flowkey calc, use switch there
  src/util/util.go
Labels: bug

#641 Misc tuning
  cmd/yggdrasilctl/main.go
  src/yggdrasil/api.go
  src/yggdrasil/dht.go
  src/yggdrasil/nodeinfo.go
  src/yggdrasil/router.go
  src/yggdrasil/search.go
Labels: needs testing
